import React from "react";
import { ArrowRight, CheckCircle2, AlertTriangle, ShieldCheck, RefreshCw, Eye, DollarSign, Phone, Mail, Menu } from "lucide-react";
import { motion } from "framer-motion";

const fadeUp = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0 } };
const stagger = { hidden: {}, visible: { transition: { staggerChildren: 0.12 } } };

function CTAButton({ children = "Book a Cash Review", dark = false }) {
  return <a href="#book" className={`group inline-flex items-center justify-center gap-3 px-8 py-5 text-lg font-black tracking-tight transition-all md:px-10 ${dark ? "bg-white text-[#0F2A44] hover:bg-slate-100" : "bg-[#F6A51A] text-black hover:bg-[#ffb638]"}`}>{children}<ArrowRight className="h-6 w-6 transition-transform group-hover:translate-x-1"/></a>;
}

const Highlight = ({ children }) => <span className="relative inline-block px-3 text-white"><span className="absolute inset-x-0 bottom-1 top-2 -z-10 -rotate-1 bg-[#1399C9]"/>{children}</span>;

function Header(){return <header className="sticky top-0 z-50 bg-[#0F2A44] text-white shadow-lg"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 md:px-8"><a href="#top" className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center border-2 border-white font-black">CC</div><div className="text-xl font-black uppercase tracking-tight md:text-2xl">Cash Control System</div></a><nav className="hidden items-center gap-8 text-sm font-bold uppercase tracking-wide md:flex"><a href="#system" className="hover:text-[#F6A51A]">System</a><a href="#outcomes" className="hover:text-[#F6A51A]">Outcomes</a><a href="#process" className="hover:text-[#F6A51A]">Process</a><a href="#faq" className="hover:text-[#F6A51A]">FAQ</a></nav><div className="hidden md:block"><CTAButton>Book a Review</CTAButton></div><button className="md:hidden" aria-label="Open menu"><Menu className="h-8 w-8"/></button></div></header>}

function Hero(){return <section id="top" className="relative overflow-hidden bg-[#0F2A44] text-white"><div className="absolute inset-0 opacity-30"><img src="https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1800&q=80" alt="Contractor job site" className="h-full w-full object-cover"/></div><div className="absolute inset-0 bg-gradient-to-b from-[#0F2A44]/85 via-[#0F2A44]/75 to-[#0F2A44]/95"/><div className="relative mx-auto max-w-6xl px-5 py-24 text-center md:px-8 md:py-32"><motion.div initial="hidden" animate="visible" variants={stagger}><motion.p variants={fadeUp} className="mb-5 text-sm font-black uppercase tracking-[0.25em] text-[#F6A51A]">Built for contractors who want cash clarity</motion.p><motion.h1 variants={fadeUp} className="mx-auto max-w-5xl text-5xl font-black leading-[0.95] tracking-tight md:text-7xl lg:text-8xl">You can’t make good decisions if you don’t know your <Highlight>cash.</Highlight></motion.h1><motion.p variants={fadeUp} className="mx-auto mt-8 max-w-3xl text-xl leading-relaxed text-white/90 md:text-2xl">We install a simple cash control system so you know how long your cash lasts, where it’s getting stuck, and what you can safely afford next.</motion.p><motion.div variants={fadeUp} className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row"><CTAButton/><p className="max-w-sm text-sm font-semibold text-white/80">We’ll walk through your cash and show you where it’s getting stuck.</p></motion.div></motion.div></div></section>}

function Problem(){const items=["You’re making decisions off today’s bank balance.","You don’t know what cash looks like 2–4 weeks out.","Receivables are drifting and nobody is chasing them hard enough.","You’re unsure if you can hire, spend, pay yourself, or take on the next job.","One wrong cash decision can create a $50K–$200K problem."];return <section className="bg-white px-5 py-20 md:px-8 md:py-28"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-[0.9fr_1.1fr] md:items-center"><motion.div initial="hidden" whileInView="visible" viewport={{once:true}} variants={fadeUp}><p className="mb-4 text-sm font-black uppercase tracking-[0.25em] text-[#1399C9]">The problem</p><h2 className="text-4xl font-black leading-tight tracking-tight text-[#0F2A44] md:text-6xl">Cash feels tight even when you’re busy.</h2></motion.div><motion.div initial="hidden" whileInView="visible" viewport={{once:true}} variants={stagger} className="rounded-2xl bg-slate-100 p-7 md:p-10">{items.map((item)=><motion.div key={item} variants={fadeUp} className="flex gap-4 border-b border-slate-200 py-5 last:border-b-0"><AlertTriangle className="mt-1 h-6 w-6 flex-none text-[#F6A51A]"/><p className="text-lg font-bold leading-snug text-[#0F2A44] md:text-xl">{item}</p></motion.div>)}</motion.div></div></section>}

const SimpleSection = ({id,title,subtitle,dark=false}) => <section id={id} className={`${dark?"bg-[#0F2A44] text-white":"bg-white text-[#0F2A44]"} px-5 py-20 md:px-8 md:py-28`}><div className="mx-auto max-w-6xl text-center"><h2 className="text-4xl font-black md:text-6xl">{title}</h2>{subtitle && <p className={`mx-auto mt-6 max-w-3xl text-xl ${dark?"text-white/80":"text-slate-700"}`}>{subtitle}</p>}</div></section>;

function Footer(){return <footer className="bg-[#081827] px-5 py-12 text-white md:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row md:items-center"><div><div className="text-2xl font-black uppercase tracking-tight">Cash Control System</div><p className="mt-2 text-white/70">See your cash. Fix the leaks. Stay in control.</p></div><div className="flex flex-col gap-3 text-white/80 md:items-end"><span className="inline-flex items-center gap-2"><Phone className="h-4 w-4"/> Book a Cash Review</span><span className="inline-flex items-center gap-2"><Mail className="h-4 w-4"/> hello@cashcontrolsystem.com</span></div></div></footer>}

export default function App(){return <main className="min-h-screen bg-white font-sans"><Header/><Hero/><Problem/><SimpleSection id="system" dark title="You don’t need more reports. You need a system." subtitle="We help you see your cash, fix where it gets stuck, and stay in control every week."/><SimpleSection id="outcomes" title="Know what you can afford. Decide with confidence."/><SimpleSection id="process" title="A 13-week install, then weekly control." subtitle="This is a working rhythm for decisions, cash timing, and action."/><SimpleSection id="faq" title="Everything else you need to know."/><section id="book" className="bg-[#0F2A44] px-5 py-20 text-center text-white md:px-8 md:py-28"><h2 className="text-4xl font-black md:text-6xl">If cash feels unclear, this fixes it.</h2><div className="mt-10"><CTAButton/></div></section><Footer/></main>}
