import React from "react";
import {
  ArrowRight,
  CheckCircle2,
  AlertTriangle,
  ShieldCheck,
  RefreshCw,
  Eye,
  DollarSign,
  Phone,
  Mail,
  Menu,
} from "lucide-react";
import { motion } from "framer-motion";

const fadeUp = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0 } };
const stagger = { hidden: {}, visible: { transition: { staggerChildren: 0.12 } } };

function CTAButton({ children = "Book a Cash Review" }) {
  return (
    <a href="#book" className="group inline-flex items-center justify-center gap-3 bg-[#F6A51A] px-8 py-5 text-lg font-black tracking-tight text-black transition-all hover:bg-[#ffb638] md:px-10">
      {children}
      <ArrowRight className="h-6 w-6 transition-transform group-hover:translate-x-1" />
    </a>
  );
}

function Header() { return <header className="sticky top-0 z-50 bg-[#0F2A44] text-white shadow-lg"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 md:px-8"><a href="#top" className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center border-2 border-white font-black">CC</div><div className="text-xl font-black uppercase tracking-tight md:text-2xl">Cash Control System</div></a><nav className="hidden items-center gap-8 text-sm font-bold uppercase tracking-wide md:flex"><a href="#system" className="hover:text-[#F6A51A]">System</a><a href="#outcomes" className="hover:text-[#F6A51A]">Outcomes</a><a href="#process" className="hover:text-[#F6A51A]">Process</a><a href="#faq" className="hover:text-[#F6A51A]">FAQ</a></nav><div className="hidden md:block"><CTAButton /></div><button className="md:hidden" aria-label="Open menu"><Menu className="h-8 w-8" /></button></div></header>; }

function Hero() { return <section id="top" className="relative overflow-hidden bg-[#0F2A44] text-white"><div className="absolute inset-0 opacity-30"><img src="https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1800&q=80" alt="Contractor job site" className="h-full w-full object-cover"/></div><div className="absolute inset-0 bg-gradient-to-b from-[#0F2A44]/85 via-[#0F2A44]/75 to-[#0F2A44]/95"/><div className="relative mx-auto max-w-6xl px-5 py-24 text-center md:px-8 md:py-32"><motion.div initial="hidden" animate="visible" variants={stagger}><motion.h1 variants={fadeUp} className="mx-auto max-w-5xl text-5xl font-black leading-[0.95] tracking-tight md:text-7xl lg:text-8xl">Busy, but your cash is still tight?</motion.h1><motion.p variants={fadeUp} className="mx-auto mt-8 max-w-3xl text-xl leading-relaxed text-white/90 md:text-2xl">We install a weekly cash control system so you know exactly how long your cash lasts, where it’s getting stuck, and what you can safely afford next.</motion.p><motion.div variants={fadeUp} className="mt-10 flex flex-col items-center gap-4"><CTAButton /><p className="max-w-lg text-sm font-semibold text-white/80">We’ll walk through your cash and show you where it’s getting stuck.</p></motion.div></motion.div></div></section>; }

function Problem() { const items=["You’re making decisions off today’s bank balance","You don’t know what cash looks like 2–4 weeks out","Receivables are drifting and nobody’s chasing them","You’re unsure if you can hire, spend, or take on the next job","One bad decision can cost $50K–$200K"]; return <section className="bg-white px-5 py-20 md:px-8 md:py-28"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-[0.9fr_1.1fr] md:items-center"><div><p className="mb-4 text-sm font-black uppercase tracking-[0.25em] text-[#1399C9]">The problem</p><h2 className="text-4xl font-black leading-tight tracking-tight text-[#0F2A44] md:text-6xl">Cash feels tight even when you’re busy.</h2></div><div className="rounded-2xl bg-slate-100 p-7 md:p-10">{items.map((i)=><div key={i} className="flex gap-4 border-b border-slate-200 py-5 last:border-b-0"><AlertTriangle className="mt-1 h-6 w-6 flex-none text-[#F6A51A]"/><p className="text-lg font-bold text-[#0F2A44] md:text-xl">{i}</p></div>)}</div></div></section>; }

function System() { const steps=[{title:"SEE", icon:Eye, color:"text-red-700", bullets:["Burn rate snapshot","Cash trap analysis"]},{title:"FIX", icon:ShieldCheck, color:"text-[#C88800]", bullets:["13-week cash forecast","Simple cash rules"]},{title:"CONTROL", icon:RefreshCw, color:"text-green-700", bullets:["Weekly cash meeting","Quarterly reset"]}]; return <section id="system" className="bg-[#0F2A44] px-5 py-20 text-white md:px-8 md:py-28"><div className="mx-auto max-w-7xl"><div className="mx-auto max-w-4xl text-center"><h2 className="text-4xl font-black md:text-6xl">The Cash Control System</h2><p className="mt-6 text-xl text-white/80">A simple system we install and run with you every week.</p></div><div className="mt-16 grid gap-6 md:grid-cols-3">{steps.map((s)=>{const I=s.icon; return <div key={s.title} className="rounded-2xl bg-white p-8 text-[#0F2A44] shadow-2xl"><I className={`h-12 w-12 ${s.color}`}/><h3 className={`mt-5 text-4xl font-black ${s.color}`}>{s.title}</h3><ul className="mt-6 space-y-3">{s.bullets.map((b)=><li key={b} className="flex items-start gap-3 font-semibold"><CheckCircle2 className="mt-0.5 h-5 w-5 text-[#F6A51A]"/>{b}</li>)}</ul></div>})}</div></div></section>; }

function Outcomes() { const cards=[{icon:Eye,title:"Clear visibility",text:"See your cash with confidence."},{icon:CheckCircle2,title:"Better decisions",text:"Know what you can afford and when."},{icon:ShieldCheck,title:"Fewer surprises",text:"Catch issues before they become problems."},{icon:DollarSign,title:"Stronger position",text:"More control. More freedom."}]; return <section id="outcomes" className="bg-white px-5 py-20 md:px-8 md:py-28"><div className="mx-auto max-w-7xl"><h2 className="mb-12 text-center text-4xl font-black text-[#0F2A44] md:text-6xl">Know what you can afford. Decide with confidence.</h2><div className="grid gap-6 md:grid-cols-4">{cards.map(({icon:Icon,title,text})=><div key={title} className="rounded-2xl border border-slate-200 bg-white p-7 shadow-sm"><Icon className="h-10 w-10 text-green-700"/><h3 className="mt-5 text-xl font-black text-[#0F2A44]">{title}</h3><p className="mt-2 text-slate-600">{text}</p></div>)}</div></div></section>; }

function BeforeAfter(){const before=["Guessing what you can afford","Payroll stress","Late collections","Surprise shortages"]; const after=["Know what you can spend","See tight weeks ahead","Clear A/R and A/P rules","Weekly cash decisions"]; return <section className="bg-slate-100 px-5 py-20 md:px-8 md:py-28"><div className="mx-auto max-w-6xl text-center"><h2 className="text-4xl font-black text-[#0F2A44] md:text-6xl">Before and after cash control.</h2><div className="mt-12 grid gap-6 md:grid-cols-2"><div className="rounded-2xl bg-white p-8 text-left"><h3 className="text-3xl font-black text-[#0F2A44]">Before</h3><ul className="mt-6 space-y-4">{before.map((x)=><li key={x} className="text-lg font-bold text-slate-700">• {x}</li>)}</ul></div><div className="rounded-2xl bg-[#0F2A44] p-8 text-left text-white"><h3 className="text-3xl font-black">After</h3><ul className="mt-6 space-y-4">{after.map((x)=><li key={x} className="text-lg font-bold">• {x}</li>)}</ul></div></div></div></section>; }

function Process(){const phases=["Phase 1: See — Weeks 1–2","Phase 2: Fix — Weeks 3–4","Phase 3: Control — Weeks 5–8","Phase 4: Optimize — Weeks 9–13"]; return <section id="process" className="bg-white px-5 py-20 md:px-8 md:py-28"><div className="mx-auto max-w-7xl"><h2 className="text-4xl font-black text-[#0F2A44] md:text-6xl">A 13-week install, then weekly control.</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{phases.map((p)=><div key={p} className="rounded-xl border border-slate-200 bg-slate-50 p-6 text-xl font-black text-[#0F2A44]">{p}</div>)}</div></div></section>; }

function Rules(){const rules=["Deposits on every job","No A/R past 60 days","No A/P past 60 days","Track job margins","Maintain cash buffer","Know your pipeline"]; return <section className="bg-[#0F2A44] px-5 py-20 text-white md:px-8 md:py-24"><div className="mx-auto max-w-7xl"><h2 className="text-center text-4xl font-black md:text-6xl">Cash control rules that stop leaks.</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{rules.map((r)=><div key={r} className="rounded-xl border border-white/15 bg-white/5 p-5 font-black">{r}</div>)}</div></div></section>; }

function FAQ(){const faqs=[["Is this bookkeeping?","No. This sits above bookkeeping and helps you lead cash decisions weekly."],["How long does it take?","The core install is designed around a 13-week process."],["What happens after 13 weeks?","You can run it internally or continue with oversight support."]]; return <section id="faq" className="bg-white px-5 py-20 md:px-8 md:py-28"><div className="mx-auto max-w-4xl"><h2 className="text-center text-4xl font-black text-[#0F2A44] md:text-6xl">Everything else you need to know.</h2><div className="mt-12 divide-y divide-slate-200">{faqs.map(([q,a])=><details key={q} className="py-6"><summary className="cursor-pointer text-xl font-black text-[#0F2A44]">{q}</summary><p className="mt-4 text-slate-700">{a}</p></details>)}</div></div></section>; }

function FinalCTA(){return <section id="book" className="bg-[#0F2A44] px-5 py-20 text-center text-white md:px-8 md:py-28"><h2 className="text-4xl font-black md:text-6xl">If cash feels unclear, this fixes it.</h2><div className="mt-10"><CTAButton /></div></section>;}
function Footer(){return <footer className="bg-[#081827] px-5 py-12 text-white md:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row md:items-center"><div><div className="text-2xl font-black uppercase">Cash Control System</div><p className="mt-2 text-white/70">See your cash. Fix the leaks. Stay in control.</p></div><div className="flex flex-col gap-3 text-white/80 md:items-end"><span className="inline-flex items-center gap-2"><Phone className="h-4 w-4"/> Book a Cash Review</span><span className="inline-flex items-center gap-2"><Mail className="h-4 w-4"/> hello@cashcontrolsystem.com</span></div></div></footer>;}

export default function App(){return <main className="min-h-screen bg-white font-sans"><Header /><Hero /><Problem /><System /><Outcomes /><BeforeAfter /><Process /><Rules /><FAQ /><FinalCTA /><Footer /></main>;}
